[package]
name = "tss-ecdsa"
version = "0.0.0"
description = "Multi-party ECDSA signing"
authors = ["Kevin Lewi <klewi@fb.com>", "Don Beaver <dbeaver@fb.com>"]
license = "MIT"
edition = "2021"
keywords = ["cryptography", "crypto", "signatures", "threshold", "ECDSA"]
categories = ["cryptography"]
readme = "README.md"

[features]
default = []
flame_it = ["flame", "flamer"]

[dependencies]
bincode = "1"
bytemuck = "1.13"
bytemuck_derive = "1.4"
displaydoc = { version = "0.2", default-features = false }
flame = { version = "0.2", optional = true }
flamer = { version = "0.3", optional = true }
generic-array = "0.14"
hex = "0.4"
k256 = { version = "0.13", features = ["arithmetic", "sha256", "ecdsa", "serde"] }
p256 = { version = "0.13.2", features = ["arithmetic", "sha256", "ecdsa", "serde"] }
lazy_static = "1"

# libpaillier depends on `unknown_order` which in turn depends on `rug`.
libpaillier = { version = "0.5", default-features = false, features = ["gmp"] }
# We don't use `rug` directly, but compilation will fail unless we include it here. See Issue #513 for more
# information.
rug = { version = "1.24.0" }

merlin = "3"
num-bigint = "0.4"
rand = "0.8"
serde = "1"
sha3 = "0.10.8"
hmac = "0.12.1"
sha2 = "0.10.8"
thiserror = "1"
tracing = "0.1.37"
zeroize = "1.5"
itertools = "0.13.0"
sodiumoxide = "0.2.7"

[dependencies.gmp-mpfr-sys]
version = "~1.6"
default-features = false

[dev-dependencies]
anyhow = "1"
clap = { version = "4.2", features = ["derive"] }
criterion = "0.3"
dialoguer = "0.10"
env_logger = "0.10.0"
glass_pumpkin = "1"
indicatif = "0.17"
openssl = "0.10"
reqwest = { version = "0.11", features = ["json"] }

rug = { version = "1.16", default-features = false, features = ["integer", "rand"] }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tokio = { version = "1", features = ["full"] }
# Generate UUID for threaded example.
uuid = { version = "1.3.3", features = ["v4", "fast-rng"] }

[[bench]]
name = "e2e_benchmark"
harness = false

[[bench]]
name = "bignumber_benchmark"
harness = false

# This isn't strictly necessary but helps certain IDEs (Clion) find the code.
[[example]]
name = "threaded_example"
path = "examples/threaded_example/threaded.rs"
